### ISSUE TITLE
PNG Image Support

### ISSUE THREAD

**Issue by emresancaktar** [NikolaKirev/OnboardKit#15]
When I add PNG Images whole background turns images. Any idea ?

**Comment by NikolaKirev** [comment]
Sounds like this might be related to #16 

Are your images larger than the onboarding page. If so, they don't downscale by design and affect the layout.

**Comment by NikolaKirev** [comment]
The `contentMode` of imageViews can now be customized using `AppearanceConfiguration`.
Closing this issue, since it can be avoided by using the proper `contentMode`.
