### ISSUE TITLE
Documentation is terrible

### ISSUE THREAD

**Issue by bamboozooled** [NikolaKirev/OnboardKit#17]
Please improve the documentation. I should not have to look into your source code to figure out which class has the function AppearanceConfiguration. That should be in the docs. Also, your cocoa pods version is behind. That should be updated as well. I had to use the Github version.

**Comment by bamboozooled** [comment]
Also, when customizing the appearance, you just have a function AppearanceConfiguration. Where does this function come from? the OnboardPage? the kit itself? No explanation as to where it's from. 

This may seem like Im being harsh but there is a picture right above that in the documentation as a developer I don't care about the picture, I care more about how the tool works and you have not done a great deal to explain that to me. Thank's for the tool but please improve the documentation.

**Comment by NikolaKirev** [comment]
Hi @bamboozooled ! Thanks for the feedback! The `AppearanceConfiguration` type is passed to an `OnboardViewController` when initialising it. I'll make sure to include it as an example in the README file. In the mean time, feel free to submit a Pull Request with any improvements you would like to see. Have a great day! 🙂

**Comment by NikolaKirev** [comment]
Updated documentation with more details on styling in version 1.3.0

**Comment by tewodroswondimu** [comment]
How do you advance to the next page programmatically?

**Comment by NikolaKirev** [comment]
Each onboard page has an optional `action` calling the completion of that action advances the page.
Please see `OnboardPage.swift` for more info.
