### ISSUE TITLE
Action Button Styling

### ISSUE THREAD

**Issue by froggomad** [NikolaKirev/OnboardKit#27]
Action Button Styling appears to have been removed as ActionButtonStyling isn't a member of OnboardKit - inspecting the pod, it doesn't appear you can customize action buttons any longer...

**Comment by NikolaKirev** [comment]
Both `advanceButtonStyling` and `actionButtonStyling` parameters are of type `ButtonStyling` and are still supported.

Closing this issue. Please let me know if the problem persists.
