### ISSUE TITLE
Delegate methods are not being called

### ISSUE THREAD

**Issue by tewodroswondimu** [NikolaKirev/OnboardKit#32]
Even though I've set the view controller as the delegate, the delegate methods don't get called. 

`
private func showAlert(_ completion: @escaping (_ success: Bool, _ error: Error?) -> Void) {
        let controller = SPPermissions.native([.notification])

        // Set Delegate if need.
        controller.delegate = self

        // Always use this method for request.
        // You can pass any controller, this request becouse need implement base protocol.
        controller.present(on: self)
    }
    
    // Events
    func didAllow(permission: SPPermission) {
        print("Allowed")
    }
    
    func didDenied(permission: SPPermission) {
        print("Denied")
    }
    
    @objc func deniedData(for permission: SPPermission) -> SPPermissionDeniedAlertData? {
        print("but it got denied")
        if permission == .notification {
            let data = SPPermissionDeniedAlertData()
            data.alertOpenSettingsDeniedPermissionTitle = "Permission denied"
            data.alertOpenSettingsDeniedPermissionDescription = "Please, go to Settings and allow permission."
            data.alertOpenSettingsDeniedPermissionButtonTitle = "Settings"
            data.alertOpenSettingsDeniedPermissionCancelTitle = "Cancel"
            return data
        } else {
            // If returned nil, alert will not show.
            return nil
        }
    }`

**Comment by NikolaKirev** [comment]
Hey @tewodroswondimu 

OnboardKit itself does not use the Delegate pattern. If you want to trigger a permission alert you would have to use the `action` parameter when creating onboard pages.

The sample code you have posted does not look related to this framework. Let me know if you still need any help or can close this issue.

**Comment by tewodroswondimu** [comment]
Hey @NikolaKirev, 

Thanks for the quick reply.  Super awesome framework too. You are indeed correct, I was using the SPPermission framework to display permission along with the OnboardKit frame and got myself confused.
