### ISSUE TITLE
Action when last page disappears

### ISSUE THREAD

**Issue by peme** [NikolaKirev/OnboardKit#34]
Any way to call a function when the last onboarding page disappears?

**Comment by ddaddy** [comment]
I was thinking the same. If you present this full screen, the underlying `viewDidAppear` is called before the completion block from the onboarding, so there's no way to set a flag to no present the onboarding again (Unless you set the flag when onboarding starts).

**Comment by peme** [comment]
I need it to be able to run a 'startup' function the app runs at every startup but when the onboarding is shown this startup call shouldn't be called till the onboarding is closed.

**Comment by peme** [comment]
Found out the functionality was already there...

Use the completion parameter, see this line from the example code.

let onboardingVC = OnboardViewController(pageItems: onboardingPages, completion: {
        print("onboarding complete")
    })
