### ISSUE TITLE
Thread 1: Fatal error: init(coder:) has not been implemented

### ISSUE THREAD

**Issue by brobee** [NikolaKirev/OnboardKit#9]
Hi,

I try to run the example, but I got a fatal error (see the subject) Any idea why? swift 4, xcode 9.2

**Comment by emresancaktar** [comment]
try to run in viewDidAppear

**Comment by NikolaKirev** [comment]
Looks like you might have modified the example and are using the unimplemented `initWithCoder` method.
Closing this issue for now, but if anyone is experiencing similar problems, please let me know.
